packages:
  # Essential packages
  - base-files
  - base-passwd
  - bash
  - dash
  - dpkg
  - libc-bin
  # Required packages
  - coreutils
  - debianutils
  - diffutils
  - e2fsprogs
  - findutils
  - grep
  - gzip
  - hostname
  - init
  - login
  - mount
  - ncurses-base
  - ncurses-bin
  - perl-base
  - sed
  - tar
  - util-linux

  - arch-test
  - mmdebstrap
  - bubblewrap
  - dosfstools
  - python3-apt
  - python3-pip
  - python3-yaml
  - python3-rich
  - python3-stevedore
  - python3-cerberus
  - python3-click
  - python3-gi
  - systemd-container
  - ostree
  - libostree-dev
  - gir1.2-glib-2.0
  - gir1.2-ostree-1.0
  - libcairo2-dev
  - libgirepository1.0-dev
  - parted
  - qemu-user-static
  - fdisk
  - reprepro
  - udev
  - systemd-boot
  - zip
  - git