repositories:
  - name: "noble"
    type: "deb"  # Repository type: rpm or deb
    baseURL: "http://ports.ubuntu.com/ubuntu-ports"
    pkgPrefix: "http://ports.ubuntu.com/ubuntu-ports"
    releaseFile: "http://ports.ubuntu.com/ubuntu-ports/dists/noble/Release"
    releaseSign: "http://ports.ubuntu.com/ubuntu-ports/dists/noble/Release.gpg"
    pbGPGKey: "/usr/share/keyrings/ubuntu-archive-keyring.gpg"
    gpgCheck: true
    repoGPGCheck: true
    enabled: true
    component: "main restricted universe multiverse"  # Repository component/section identifier
    buildPath: "./builds/ubuntu24/aarch64-main"  # Will be replaced with temp_dir/builds/ubuntu24/aarch64-main at runtime
  - name: "noble-security"
    type: "deb"
    baseURL: "http://ports.ubuntu.com/ubuntu-ports"
    pkgPrefix: "http://ports.ubuntu.com/ubuntu-ports"
    releaseFile: "http://ports.ubuntu.com/ubuntu-ports/dists/noble-security/Release"
    releaseSign: "http://ports.ubuntu.com/ubuntu-ports/dists/noble-security/Release.gpg"
    pbGPGKey: "/usr/share/keyrings/ubuntu-archive-keyring.gpg"
    gpgCheck: true
    repoGPGCheck: true
    enabled: true
    component: "main restricted universe multiverse"
    buildPath: "./builds/ubuntu24/aarch64-security"  # Will be replaced with temp_dir/builds/ubuntu24/aarch64-security at runtime
  - name: "noble-updates"
    type: "deb"
    baseURL: "http://ports.ubuntu.com/ubuntu-ports"
    pkgPrefix: "http://ports.ubuntu.com/ubuntu-ports"
    releaseFile: "http://ports.ubuntu.com/ubuntu-ports/dists/noble-updates/Release"
    releaseSign: "http://ports.ubuntu.com/ubuntu-ports/dists/noble-updates/Release.gpg"
    pbGPGKey: "/usr/share/keyrings/ubuntu-archive-keyring.gpg"
    gpgCheck: true
    repoGPGCheck: true
    enabled: true
    component: "main restricted universe multiverse"
    buildPath: "./builds/ubuntu24/aarch64-updates"  # Will be replaced with temp_dir/builds/ubuntu24/aarch64-updates at runtime
